# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy HTML site to Azure Web App - gadmunicipalchontaduro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_81E24103CEE343F3BDA6EE5B10F90443 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_95EA287671CF4169953E4D70BD7138B8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A38B34FBE59D44AAB6C027D980F733D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: gadmunicipalchontaduro
          slot-name: Production
          package: .

          
